services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/configs"
      - "--entrypoints.web.address=:80"
    ports:
      - "85:85"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs:/configs
    networks:
      - web

  nginx_app_1:
    image: nginx:latest
    labels:
      - "traefik.enable=false"
    ports:
      - "90:90"
      - "8090:8090"
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - web

  nginx_app_2:
    image: nginx:latest
    labels:
      - "traefik.enable=false"
    ports:
      - "95:95"
      - "8095:8095"
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - web

networks:
  web:
    driver: bridge
